### ISSUE TITLE
TypeError: promisify is not a function

### ISSUE THREAD

**Issue by tobeorla** [toajs/quic#4]
**Code:**
```js
var server = require('quic')
server.listen(app);

server.on('error', function(d) {
  console.error('echo', d);
});

server.on('message', function(a,b,c,d) {
  console.log('received :',a,b,c,d);
});
```
**Version:** 0.02
**Full trace:**
```
C:\Users\yo\Desktop\test\node_modules\quic\lib\common.js:8
exports.lookup = promisify(require('dns').lookup)
                 ^

TypeError: promisify is not a function
    at Object.<anonymous> (C:\Users\yo\Desktop\test\node_modules\quic\lib\common.js:8:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\yo\Desktop\test\node_modules\quic\lib\tag.js:6:21)
    at Module._compile (module.js:541:32)
```

Edit:
As i see, quic requires node >= 8, i have node 6 and npm let me install it without any warning : s

**Comment by zensh** [comment]
Sorry, the project is worked in progress
